services:
  api-gateway:
    build: ./api-gateway
    ports:
      - 3000:3000
      - 9220:9220
    volumes:
      - ./api-gateway:/app # Sync code with container
      - /app/node_modules # Ignore node_modules
    env_file:
      - ./api-gateway/.env
    environment:
      - REDIS_HOST=redis
      - IDENTITY_SERVICE_URL=http://identity-service:3001
      - PROJECT_SERVICE_URL=http://project-service:3002
      - UPLOAD_SERVICE_URL=http://upload-service:3003
      - CONTENT_SERVICE_URL=http://content-service:3004
      - NOTIFICATION_SERVICE_URL=http://notification-service:3005
    depends_on:
      - redis

  identity-service:
    build: ./identity-service
    ports:
      - 3001:3001
      - 9221:9221
    volumes:
      - ./identity-service:/app # Sync code with container
      - /app/node_modules # Ignore node_modules
    env_file:
      - ./identity-service/.env
    environment:
      - REDIS_HOST=redis
      - RABBITMQ_URL=amqp://rabbitmq
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_started

  project-service:
    build: ./project-service
    ports:
      - 3002:3002
      - 9222:9222
    volumes:
      - ./project-service:/app # Sync code with container
      - /app/node_modules # Ignore node_modules
    env_file:
      - ./project-service/.env
    environment:
      - REDIS_HOST=redis
      - RABBITMQ_URL=amqp://rabbitmq
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_started

  upload-service:
    build: ./upload-service
    ports:
      - 3003:3003
      - 9223:9223
    volumes:
      - ./upload-service:/app # Sync code with container
      - /app/node_modules # Ignore node_modules
    env_file:
      - ./upload-service/.env
    environment:
      - REDIS_HOST=redis
      - RABBITMQ_URL=amqp://rabbitmq
      - PROJECT_SERVICE_URL=http://project-service:3002
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_started

  content-service:
    build: ./content-service
    ports:
      - 3004:3004
      - 9224:9224
    volumes:
      - ./content-service:/app # Sync code with container
      - /app/node_modules # Ignore node_modules
    env_file:
      - ./content-service/.env
    environment:
      - REDIS_HOST=redis
      - RABBITMQ_URL=amqp://rabbitmq
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_started

  notification-service:
    build: ./notification-service
    ports:
      - 3005:3005
      - 9225:9225
    volumes:
      - ./notification-service:/app # Sync code with container
      - /app/node_modules # Ignore node_modules
    env_file:
      - ./notification-service/.env
    environment:
      - REDIS_HOST=redis
      - RABBITMQ_URL=amqp://rabbitmq
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_started

  redis:
    image: redis:7.4.0
    ports:
      - 6379:6379

  rabbitmq:
    image: rabbitmq:4.0.7-management
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 6s
      timeout: 3s
      retries: 5
