services:
  app:
    build: .
    ports:
      - 3003:3003
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
      - RABBITMQ_URL=amqp://rabbitmq
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_started

  redis:
    image: redis:7.4.0
    ports:
      - 6379:6379

  rabbitmq: 
    image: rabbitmq:management
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "ping" ]
      interval: 6s
      timeout: 3s
      retries: 5